export const areasState = [
  {
    id: 0,
    name: "Kokiri Forest",
    short: "kf",
    checks: [
      {
        id: 0,
        name: "Mido 1",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Mido 2",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Mido 3",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Mido 4",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "KS chest",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "SoS grotto",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Link's Cow",
        reachable: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Shop 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Shop 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Shop 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Shop 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 1,
    name: "Lost Woods",
    short: "lw",
    checks: [
      {
        id: 0,
        name: "Skull Kid",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Free Scrub",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Target",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Ocarina game",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Grotto",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull Mask",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 6,
        name: "L.Scrub theater",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 7,
        name: "R.Scrub theater",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub left gr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Scrub right gr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Ocarina",
        reachable: false,
        checked: false,
        player: "",
        setting: "shuffle ocarina",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 2,
    name: "SFM",
    short: "sfm",
    checks: [
      {
        id: 0,
        name: "Saria",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Minuet",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Wolfos grotto",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub sos 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Scrub sos 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 3,
    name: "Deku",
    short: "dek",
    entrance:"deku",
    checks: [
      {
        id: 0,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Little chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Slingshot",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Near compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "B1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "B1 Skull",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "B1 Skull Vine",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Back Skull",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Gohma",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 4,
    name: "Forest",
    short: "for",
    entrance:"forest",
    keysLeft:5,
    maxKeys:5,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Skull tree",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Tree",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Skull Stalfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Stalfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Garden chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull garden",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "High chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Well chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Eye",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Floormaster",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Skull arch",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "BK chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Red",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Bow chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Blue",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Plafondbro",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "French room",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "French Skull",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "P. Ganon",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 5,
    name: "Hyrule Field",
    short: "hf",
    checks: [
      {
        id: 0,
        name: "SoT",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 1,
        name: "Open grotto",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Remote",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Boulda",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Tektile",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Cow",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Ocarina of time",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shuffle ocarina",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 6,
    name: "Ranch",
    short: "ran",
    checks: [
      {
        id: 0,
        name: "Epona",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Cow 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Cow 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Talon",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Freestanding",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Cow 4",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Cow 5",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 1",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub 2",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Scrub 3",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 7,
    name: "Lake Hylia",
    short: "lh",
    checks: [
      {
        id: 0,
        name: "Child fishing",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Underwater",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Adult fishing",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Rooftop",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Diving",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Shoot the sun",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Scrub",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 8,
    name: "Water",
    short: "wat",
    entrance:"water",
    keysLeft:6,
    maxKeys:6,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Skull gate",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Broken wall",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Torches",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull b4 BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Eye",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Skull pillar",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Pillar",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Skull plats",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Dark Link",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Skull river",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "River",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Dragon",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Morpha",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 9,
    name: "Market",
    short: "mar",
    checks: [
      {
        id: 0,
        name: "Sling MG",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Kiki",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Bowling",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Bowling",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "CMG",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Big poe",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Bazaar 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Bazaar 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Bazaar 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Bazaar 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Potion 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Potion 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Potion 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Potion 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Chu shop 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Chu shop 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Chu shop 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Chu shop 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 10,
    name: "Temple of Time",
    short: "tot",
    checks: [
      {
        id: 0,
        name: "Prelude",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        song: true,
        item: "",
      },
      {
        id: 1,
        name: "Light arrows",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        song: false,
        item: "",
      },
    ],
  },
  {
    id: 11,
    name: "Hyrule Castle",
    short: "hc",
    checks: [
      {
        id: 0,
        name: "Din's Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 12,
    name: "Outside G's C",
    short: "out",
    checks: [
      {
        id: 0,
        name: "DD Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 13,
    name: "Kakariko",
    short: "kak",
    checks: [
      {
        id: 0,
        name: "SoS",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Nocturne",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Cuccos",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Lazy dude",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Free gr.",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Windmill",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Archerie",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Anju",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Cow PoH",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Cow",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Redead gr.",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "10s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "20s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "30s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 14,
        name: "40s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 15,
        name: "50s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 16,
        name: "Bazaar 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 17,
        name: "Bazaar 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 18,
        name: "Bazaar 3",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 19,
        name: "Bazaar 4",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 20,
        name: "Potion 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 21,
        name: "Potion 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 22,
        name: "Potion 3",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
      {
        id: 23,
        name: "Potion 4",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
        price :"",
      },
    ],
  },
  {
    id: 14,
    name: "Graveyard",
    short: "gy",
    checks: [
      {
        id: 0,
        name: "Sun song",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Free tomb",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Dampe tour",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Item box",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Dampe race",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Dampe race",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Playing Sun",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Royal torches",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 15,
    name: "Bot. of the Well",
    short: "wel",
    entrance:"botw",
    keysLeft:3,
    maxKeys:3,
    checks: [
      {
        id: 0,
        name: "Bomb entrance",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Left chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Right chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Skull chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Skull central 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull central 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Bomb back",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Chest b4 coffin",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Coffin",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Chest b4 D.hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Dead hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Invisible chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Fire Keeses",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Like Like",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Skull Like Like",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Basement",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 16,
    name: "Shadow",
    short: "sha",
    entrance:"shadow",
    keysLeft:5,
    maxKeys:5,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Hovers",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Silver rupees",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Skull spin",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Spinning 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Spinning 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Spike high 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Spike high 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Spike low",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Skull in jail",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Redead rupees",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Skull pot",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Pot",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Wind",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Last Gibdos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Bombable",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Skull b4 boat",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Near BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "Skull 3 pots",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Floormaster",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 22,
        name: "Bongo",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 17,
    name: "DMT",
    short: "dmt",
    checks: [
      {
        id: 0,
        name: "Free HP",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Wall",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Sos grotto",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Biggoron",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 5,
        name: "Cow",
        reachable: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
    ],
  },
  {
    id: 18,
    name: "Goron city",
    short: "gc",
    checks: [
      {
        id: 0,
        name: "Big rolling",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Darunia",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Pot",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Link the Goron",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Right Maze 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Right Maze 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Left Maze",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Scrub 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Shop 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
        price:"",
      },
      {
        id: 11,
        name: "Shop 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
        price:"",
      },
      {
        id: 12,
        name: "Shop 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
        price:"",
      },
      {
        id: 13,
        name: "Shop 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
        price:"",
      },
      {
        id: 14,
        name: "Medigoron",
        reachable: false,
        checked: false,
        player: "",
        setting: "medigoron & carpet salesman",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 19,
    name: "DMC",
    short: "dmc",
    checks: [
      {
        id: 0,
        name: "Bolero",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Crater HP",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Wall HP",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Fairy",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Grotto",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Scrub 1",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Scrub 2",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 3",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 20,
    name: "Dodongo's Cav.",
    short: "dc",
    entrance:"dc",
    checks: [
      {
        id: 0,
        name: "Skull crow",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Skull keeses",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Scrub switch",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub main room",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Skull Nook",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Skull Vines",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Spike",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Bomb bag",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Scrub BB 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Scrub BB 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Bridge",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Skull armos",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Above KD",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "King Dodongos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 21,
    name: "Fire",
    short: "fir",
    entrance:"fire",
    keysLeft:8,
    maxKeys:8,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Near boss",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Skull Dancer",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Dancer 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "BK chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Lava room",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull SoT",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Lava room bomb",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Maze lower chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Skull maze",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Side room",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Upper Goron",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Shortcut chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Skull Pierre 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Skull Pierre 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Pierre",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "SoT chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Hammer chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Volvagia",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 22,
    name: "Zora's river",
    short: "zr",
    checks: [
      {
        id: 0,
        name: "Pillar HP",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Scrub",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Scrub",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Frogs Sos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Frogs 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 5,
        name: "Free grotto",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Waterfall HP",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 23,
    name: "Zora's domain",
    short: "zd",
    checks: [
      {
        id: 0,
        name: "Torches",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Rupees MG",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "King Zora",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Shop 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Shop 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Shop 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Shop 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 24,
    name: "Zora's fountain",
    short: "zf",
    checks: [
      {
        id: 0,
        name: "Iceberg",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Icy waters",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 25,
    name: "Jabu",
    short: "jab",
    entrance:"jabu",
    checks: [
      {
        id: 0,
        name: "Skull Stingers",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Scrub Octo",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Boomerang",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skull big Octo 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Skull big Octo 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Skull Barinade",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Barinade",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 26,
    name: "Ice Cavern",
    short: "ic",
    entrance:"ice",
    checks: [
      {
        id: 0,
        name: "Serenade",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: true,
      },
      {
        id: 1,
        name: "Skull spin",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 2,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 3,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 4,
        name: "Skull bl.fire",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 5,
        name: "Freestanding",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 6,
        name: "Skull blocks",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 7,
        name: "Iron boots",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
    ],
  },
  {
    id: 27,
    name: "Gerudo's Valley",
    short: "gv",
    checks: [
      {
        id: 0,
        name: "Box",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Waterfall HP",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Cow",
        reachable: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Rocks",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Scrub SoS 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Scrub SoS 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 28,
    name: "Gerudo's Fortress",
    short: "gf",
    checks: [
      {
        id: 0,
        name: "Rooftop",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "1000 pts",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "1500 pts",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 29,
    name: "Wasteland",
    short: "was",
    checks: [
      {
        id: 0,
        name: "Carpet Salesman",
        reachable: false,
        checked: false,
        player: "",
        setting: "medigoron & carpet salesman",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Torches",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 30,
    name: "Desert Colossus",
    short: "col",
    checks: [
      {
        id: 0,
        name: "Requiem",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Arch",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Scrub 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 31,
    name: "GTG",
    short: "gtg",
    entrance:"gtg",
    keysLeft:9,
    maxKeys:9,
    checks: [
      {
        id: 0,
        name: "Eye 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Eye 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Stalfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Wolfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Block 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Block 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Block 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Block 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Statue",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Above statue",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Keeses & Slugs",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Fire chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "SoT freestanding",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "SoT chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "SoT chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Toilets",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Beamos & Dino",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Left maze 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Left maze 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Left maze 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "Left maze 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Final thieves",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 32,
    name: "Spirit",
    short: "spi",
    entrance:"spirit",
    keysLeft:5,
    maxKeys:5,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Child crystal",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Child keese",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Skull gate",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Skull climb",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Child climb",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Child climb",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Sun block",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Skull knuckle",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Right hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Adult left",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Skull SoT",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Adult right",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Mirror room 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Mirror room 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Lullaby high",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Lullaby hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Skull statue",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Armors sun",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Invisible 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "Invisible 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Mirror shld",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 22,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 23,
        name: "Last sun",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 24,
        name: "Twinrova",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 33,
    name: "Ganon's Castle",
    short: "gan",
    entrance:"ganon",
    keysLeft:2,
    maxKeys:2,
    checks: [
      {
        id: 0,
        name: "Scrub 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Scrub 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Scrub 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Forest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Water 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Water 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Shadow 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Shadow 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Light 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Light 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Light 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Light 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Light 5",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Light 6",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Light clr",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Light key",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Spirit 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Spirit 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Boss key",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
];
