export const areasState = [
  {
    id: 0,
    name: "Kokiri Forest",
    short: "kf",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Mido 1",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Mido 2",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Mido 3",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Mido 4",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "K.Sword",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "SoS gr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Link's Cow",
        reachable: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Shop 1",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Shop 2",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Shop 3",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Shop 4",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 1,
    name: "Lost Woods",
    short: "lw",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Skll Kid",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Fr. Scrub",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Target",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Oca. game",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Grotto",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll Mask",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 6,
        name: "L.Scrub theater",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 7,
        name: "R.Scrub theater",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 8,
        name: "L.Scrub gr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "R.Scrub gr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Ocarina",
        reachable: false,
        checked: false,
        player: "",
        setting: "shuffle ocarina",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 2,
    name: "SFM",
    short: "sfm",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Saria",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Minuet",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Wolfos gr.",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub sos 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Scrub sos 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 3,
    name: "Deku",
    short: "dek",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"deku",
    checks: [
      {
        id: 0,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Sling 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Sling 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "N. compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "B1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "B1 Skll",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "B1 Skll Vine",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Back Skull",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Gohma",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 4,
    name: "Forest",
    short: "for",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"forest",
    keysLeft:5,
    maxKeys:5,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Skll tree",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Tree",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Skll Stalfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Stalfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Garden",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll garden",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Bubble",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Well",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Eye",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Floormstr",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Skll arch",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Red",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Bow",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Blue",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Ceiling",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "French room",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "French Skll",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "P.Ganon",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 5,
    name: "Hyrule Field",
    short: "hf",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "SoT",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 1,
        name: "Open gr.",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Remote",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Boulda",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Tektile",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Cow",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "OoT",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "shuffle ocarina",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 6,
    name: "Ranch",
    short: "ran",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Epona",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Cow 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Cow 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Talon",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Freest.",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Cow 4",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Cow 5",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 1",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub 2",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Scrub 3",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 7,
    name: "Lake Hylia",
    short: "lh",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Chld fish.",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Underwater",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Adlt fish.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Rooftop",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Diving",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Shoot. sun",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Scrub 1",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 2",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub 3",
        reachable: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 8,
    name: "Water",
    short: "wat",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"water",
    keysLeft:6,
    maxKeys:6,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Skll gate",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Broken wall",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Torches",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll b4 BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Eye",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Skll pillar",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Pillar",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Skll plats",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Dark Link",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Skll river",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "River",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Dragon",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Morpha",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 9,
    name: "Market",
    short: "mar",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Sling MG",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Kiki",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Bowling",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Bowling",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "CMG",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Big poe",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Bazaar 1",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Bazaar 2",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Bazaar 3",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Bazaar 4",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Potion 1",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Potion 2",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Potion 3",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Potion 4",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Chu shop 1",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Chu shop 2",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Chu shop 3",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Chu shop 4",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 10,
    name: "Temple of Time",
    short: "tot",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Prelude",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        song: true,
        item: "",
      },
      {
        id: 1,
        name: "Light arr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        song: false,
        item: "",
      },
    ],
  },
  {
    id: 11,
    name: "Hyrule Castle",
    short: "hc",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Dins Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 12,
    name: "Outside G's C",
    short: "out",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "DD Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 13,
    name: "Kakariko",
    short: "kak",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "SoS",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Nocturne",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Cuccos",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Lazy dude",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Free gr.",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Windmill",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Archrie",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Anju",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Cow PoH",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Cow",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Redead gr.",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "10s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "20s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "30s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 14,
        name: "40s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 15,
        name: "50s",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 16,
        name: "Bazaar 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Bazaar 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Bazaar 3",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Bazaar 4",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "Potion 1",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Potion 2",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 22,
        name: "Potion 3",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 23,
        name: "Potion 4",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 14,
    name: "Graveyard",
    short: "gy",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Sun song",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Free tomb",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Dampe tour",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Item box",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Race 1",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Race 2",
        reachable: true,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Play. Sun",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Royal torch.",
        reachable: false,
        song: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 15,
    name: "Well",
    short: "wel",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"well",
    keysLeft:3,
    maxKeys:3,
    checks: [
      {
        id: 0,
        name: "Bomb entr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Left entr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Right entr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Skll chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Skll key 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll key 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Bomb bck",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "b4 coffin",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Coffin",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "b4 D.hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Dead hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Invsble",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Keeses",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Like Like",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Skll Like",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Basement",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 16,
    name: "Shadow",
    short: "sha",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"shadow",
    keysLeft:5,
    maxKeys:5,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Hovers",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Silv. rup.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Skll spin",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Spin. 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Spin. 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Spike h1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Spike h2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Spike low",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Skll jail",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Redead rup.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Skll pot",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Pot",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Wind",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Gibdos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Bombable",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Skll boat",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Near BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "Skll 3pots",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Floormstr",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 22,
        name: "Bongo",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 17,
    name: "DMT",
    short: "dmt",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Free HP",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Wall",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Sos gr.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Biggoron",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 5,
        name: "Cow",
        reachable: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
    ],
  },
  {
    id: 18,
    name: "Goron city",
    short: "gc",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Big roll.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Darunia",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Pot",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Link",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "R. Maze 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "R. Maze 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "L. Maze",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Scrub 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Scrub 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Shop 1",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Shop 2",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Shop 3",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Shop 4",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Medigoron",
        reachable: false,
        checked: false,
        player: "",
        setting: "medigoron & carpet salesman",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 19,
    name: "DMC",
    short: "dmc",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Bolero",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Crater HP",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Wall HP",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Fairy",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Grotto",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Scrub 1",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Scrub 2",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Scrub 3",
        reachable: false,
        song: true,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 20,
    name: "Dodongo's Cav.",
    short: "dc",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"dc",
    checks: [
      {
        id: 0,
        name: "Skll crow",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Skll keeses",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Scrub switch",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub main r.",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Skll Nook",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Skll Vines",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Spike",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Bomb bag",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Scrub BB 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Scrub BB 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Bridge",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Skll armos",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Above KD",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "King Do.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 21,
    name: "Fire",
    short: "fir",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"fire",
    keysLeft:8,
    maxKeys:8,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Near boss",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Skll Dancer",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Dancer 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "BK chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Lava room",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll SoT",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Lava room bb",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Maze low",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Skll maze",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Side room",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Upper Goron",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Shortcut",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Skll Crow 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Skll Crow 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Pierre",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "SoT",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Hammer",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Volvagia",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 22,
    name: "Zora's river",
    short: "zr",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Pillar HP",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Scrub",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Scrub",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Frogs Sos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Frogs 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        hintBox: false,
        item: "",
      },
      {
        id: 5,
        name: "Free gr.",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Waterfall HP",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 23,
    name: "Zora's domain",
    short: "zd",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Torches",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Rup. MG",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "King Zora",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Shop 1",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Shop 2",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Shop 3",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Shop 4",
        reachable: false,
        checked: false,
        player: "",
        rupee:"",
        setting: "shopsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 24,
    name: "Zora's fountain",
    short: "zf",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Iceberg",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Icy wat.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 25,
    name: "Jabu",
    short: "jab",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"jabu",
    checks: [
      {
        id: 0,
        name: "Skll Stinger",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Scrub",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Boomrng",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Skll basem. 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Skull basem. 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Skll Bar.",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Barinade",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 26,
    name: "Ice Cavern",
    short: "ic",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"ice cavern",
    checks: [
      {
        id: 0,
        name: "Serenade",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: true,
      },
      {
        id: 1,
        name: "Skll spin",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 2,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 3,
        name: "Compass",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 4,
        name: "Skull fire",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 5,
        name: "Freestand.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 6,
        name: "Skll blocks",
        reachable: false,
        checked: false,
        player: "",
        setting: "skullsanity",
        visibility: false,
        box: false,
        item: "",
        song: false,
      },
      {
        id: 7,
        name: "Iron boots",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        box: false,
        item: "",
        song: false,
      },
    ],
  },
  {
    id: 27,
    name: "Gerudo's Valley",
    short: "gv",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Box",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Waterfall HP",
        reachable: true,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Cow",
        reachable: false,
        checked: false,
        player: "",
        setting: "cowsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Rocks",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Scrub SoS 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Scrub SoS 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 28,
    name: "Gerudo's Fortress",
    short: "gf",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Rooftop",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "1000 pts",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "1500 pts",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 29,
    name: "Wasteland",
    short: "was",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Carpet Sale.",
        reachable: false,
        checked: false,
        player: "",
        setting: "medigoron & carpet salesman",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Torches",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 30,
    name: "Desert Colossus",
    short: "col",
    visibility:true,
    checks: [
      {
        id: 0,
        name: "Requiem",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: true,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Fairy",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Arch",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Scrub 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 31,
    name: "GTG",
    short: "gtg",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"gtg",
    keysLeft:9,
    maxKeys:9,
    checks: [
      {
        id: 0,
        name: "Eye 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Eye 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Stalfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Wolfos",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Block 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Block 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Block 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Block 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Statue",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Abo. statue",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Keeses&Slugs",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Fire chest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Freestand.",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "SoT 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "SoT 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Toilets",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Beamos&Dino",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "L.maze 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "L.maze 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "L.maze 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "L.maze 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Final",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 32,
    name: "Spirit",
    short: "spi",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"spirit",
    keysLeft:5,
    maxKeys:5,
    bossKeyLeft:1,
    maxBossKey:1,
    checks: [
      {
        id: 0,
        name: "Chld crystal",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Chld keese",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Skll gate",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Skll climb",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Climb 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Climb 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Map",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Sun block",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Skll knckle",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "R. hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "L.Adlt",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Skll SoT",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "R.Adlt",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Mirror 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Mirror 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Lul. high",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Lul. hand",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Skll statue",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Armors sun",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Invsble 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 20,
        name: "Invsble 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 21,
        name: "Mir. shld",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 22,
        name: "BK",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 23,
        name: "Last sun",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 24,
        name: "Twinrova",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
  {
    id: 33,
    name: "Ganon's Castle",
    short: "gan",
    visibility:true,
    dungeonShuffleInput:"",
    entrance:"ganon",
    keysLeft:2,
    maxKeys:2,
    checks: [
      {
        id: 0,
        name: "Scrub 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 1,
        name: "Scrub 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 2,
        name: "Scrub 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 3,
        name: "Scrub 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "scrubsanity",
        visibility: false,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 4,
        name: "Forest",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 5,
        name: "Water 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 6,
        name: "Water 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 7,
        name: "Shadow 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 8,
        name: "Shadow 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 9,
        name: "Light 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 10,
        name: "Light 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 11,
        name: "Light 3",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 12,
        name: "Light 4",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 13,
        name: "Light 5",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 14,
        name: "Light 6",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 15,
        name: "Light clr",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 16,
        name: "Light key",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 17,
        name: "Spirit 1",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 18,
        name: "Spirit 2",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
      {
        id: 19,
        name: "Boss key",
        reachable: false,
        checked: false,
        player: "",
        setting: "none",
        visibility: true,
        song: false,
        box: false,
        item: "",
      },
    ],
  },
];
