export const dungeonsKeys = [
    {
      id: 0,
      name: "Small key Forest",
      image: `${process.env.PUBLIC_URL}/assets/small_key.png`,
      nb: 0,
      limit: 5,
    },
    {
      id: 1,
      name: "Boss key Forest",
      image: `${process.env.PUBLIC_URL}/assets/boss_key.png`,
      nb: 0,
      limit: 1,
    },
    {
      id: 2,
      name: "Small key Fire",
      image: `${process.env.PUBLIC_URL}/assets/small_key.png`,
      nb: 0,
      limit: 8,
    },
    {
      id: 3,
      name: "Boss key Fire",
      image: `${process.env.PUBLIC_URL}/assets/boss_key.png`,
      nb: 0,
      limit: 1,
    },
    {
      id: 4,
      name: "Small key Water",
      image: `${process.env.PUBLIC_URL}/assets/small_key.png`,
      nb: 0,
      limit: 6,
    },
    {
      id: 5,
      name: "Boss key Water",
      image: `${process.env.PUBLIC_URL}/assets/boss_key.png`,
      nb: 0,
      limit: 1,
    },
    {
      id: 6,
      name: "Small key Shadow",
      image: `${process.env.PUBLIC_URL}/assets/small_key.png`,
      nb: 0,
      limit: 5,
    },
    {
      id: 7,
      name: "Boss key Shadow",
      image: `${process.env.PUBLIC_URL}/assets/boss_key.png`,
      nb: 0,
      limit: 1,
    },
    {
      id: 8,
      name: "Small key Spirit",
      image: `${process.env.PUBLIC_URL}/assets/boss_key.png`,
      nb: 0,
      limit: 5,
    },
    {
      id: 9,
      name: "Boss key Spirit",
      image: `${process.env.PUBLIC_URL}/assets/boss_key.png`,
      nb: 0,
      limit: 1,
    },
    {
      id: 10,
      name: "Small key BOTW",
      image: `${process.env.PUBLIC_URL}/assets/small_key.png`,
      nb: 0,
      limit: 3,
    },
    {
      id: 11,
      name: "Small key GTG",
      image: `${process.env.PUBLIC_URL}/assets/small_key.png`,
      nb: 0,
      limit: 9,
    },
  ];