export const trackerState = [
  {
    items: [
      {
        id: 0,
        name: "Hookshot",
        image: [
          `${process.env.PUBLIC_URL}/assets/hookshot.png`,
          `${process.env.PUBLIC_URL}/assets/longshot.png`,
        ],
        number: 0,
        limit: 2,
      },
      {
        id: 1,
        name: "Bow",
        image: [`${process.env.PUBLIC_URL}/assets/bow.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 2,
        name: "Fire arrows",
        image: [`${process.env.PUBLIC_URL}/assets/fire_arrows.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 3,
        name: "Light arrows",
        image: [`${process.env.PUBLIC_URL}/assets/light_arrows.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 4,
        name: "Ocarina",
        image: [
          `${process.env.PUBLIC_URL}/assets/ocarina.png`,
          `${process.env.PUBLIC_URL}/assets/ocarina_2.png`,
        ],
        number: 0,
        limit: 2,
      },
      {
        id: 5,
        name: "Lens of truth",
        image: [`${process.env.PUBLIC_URL}/assets/lens.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 6,
        name: "Dins",
        image: [`${process.env.PUBLIC_URL}/assets/dins_fire.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 7,
        name: "Farore's Wind",
        image: [`${process.env.PUBLIC_URL}/assets/farores_wind.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 8,
        name: "Slingshot",
        image: [`${process.env.PUBLIC_URL}/assets/slingshot.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 9,
        name: "Boomerang",
        image: [`${process.env.PUBLIC_URL}/assets/boomerang.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 10,
        name: "Hammer",
        image: [`${process.env.PUBLIC_URL}/assets/hammer.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 11,
        name: "Bomb bag",
        image: [`${process.env.PUBLIC_URL}/assets/bomb.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 12,
        name: "Bottle",
        image: [`${process.env.PUBLIC_URL}/assets/bottle.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 13,
        name: "Big Poe",
        image: [`${process.env.PUBLIC_URL}/assets/big_poe.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 14,
        name: "Ruto's Letter",
        image: [`${process.env.PUBLIC_URL}/assets/rutos_letter.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 15,
        name: "Kokiri's sword",
        image: [`${process.env.PUBLIC_URL}/assets/kokiri_sword.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 16,
        name: "Bomb chu",
        image: [`${process.env.PUBLIC_URL}/assets/chu.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 17,
        name: "Scale",
        image: [
          `${process.env.PUBLIC_URL}/assets/silver_scale.png`,
          `${process.env.PUBLIC_URL}/assets/golden_scale.png`,
        ],
        number: 0,
        limit: 2,
      },
      {
        id: 18,
        name: "Strength",
        image: [
          `${process.env.PUBLIC_URL}/assets/goron_bracelet.png`,
          `${process.env.PUBLIC_URL}/assets/silver_gauntlets.png`,
          `${process.env.PUBLIC_URL}/assets/golden_gauntlets.png`,
        ],
        number: 0,
        limit: 3,
      },
      {
        id: 19,
        name: "Mirror Shield",
        image: [`${process.env.PUBLIC_URL}/assets/mirror_shield.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 20,
        name: "Magic meter",
        image: [
          `${process.env.PUBLIC_URL}/assets/magic.png`,
          `${process.env.PUBLIC_URL}/assets/magic_2.png`,
        ],
        number: 0,
        limit: 2,
      },
      {
        id: 21,
        name: "Wallet",
        image: [
          `${process.env.PUBLIC_URL}/assets/adults_wallet.png`,
          `${process.env.PUBLIC_URL}/assets/giants_wallet.png`,
        ],
        number: 0,
        limit: 2,
      },
      {
        id: 22,
        name: "Gerudo card",
        image: [`${process.env.PUBLIC_URL}/assets/gerudo_card.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 23,
        name: "Goron Tunic",
        image: [`${process.env.PUBLIC_URL}/assets/goron_tunic.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 24,
        name: "Zora Tunic",
        image: [`${process.env.PUBLIC_URL}/assets/zora_tunic.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 25,
        name: "Prescription",
        image: [
          `${process.env.PUBLIC_URL}/assets/prescription.png`,
          `${process.env.PUBLIC_URL}/assets/eyeball_frog.png`,
          `${process.env.PUBLIC_URL}/assets/eyedrops.png`,
          `${process.env.PUBLIC_URL}/assets/claim_check.png`,
        ],
        number: 0,
        limit: 4,
      },
      {
        id: 26,
        name: "Keaton Mask",
        image: [
          `${process.env.PUBLIC_URL}/assets/keaton_mask.png`,
          `${process.env.PUBLIC_URL}/assets/skull_mask.png`,
        ],
        number: 0,
        limit: 2,
      },
      {
        id: 27,
        name: "Iron boots",
        image: [`${process.env.PUBLIC_URL}/assets/iron_boots.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 28,
        name: "Hover boots",
        image: [`${process.env.PUBLIC_URL}/assets/hover_boots.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 29,
        name: "Skull Token",
        image: [`${process.env.PUBLIC_URL}/assets/skull_token.png`],
        number: 0,
        limit: 100,
      },
    ],
  },
  {
    songs: [
      {
        id: 0,
        name: "Zelda's Lullaby",
        image: [`${process.env.PUBLIC_URL}/assets/lullaby.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 1,
        name: "Epona",
        image: [`${process.env.PUBLIC_URL}/assets/eponas.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 2,
        name: "Saria",
        image: [`${process.env.PUBLIC_URL}/assets/sarias.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 3,
        name: "Sun Song",
        image: [`${process.env.PUBLIC_URL}/assets/suns_song.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 4,
        name: "Song of Time",
        image: [`${process.env.PUBLIC_URL}/assets/time.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 5,
        name: "Song of Storms",
        image: [`${process.env.PUBLIC_URL}/assets/storms.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 6,
        name: "Minuet",
        image: [`${process.env.PUBLIC_URL}/assets/minuet.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 7,
        name: "Boléro",
        image: [`${process.env.PUBLIC_URL}/assets/bolero.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 8,
        name: "Sérénade",
        image: [`${process.env.PUBLIC_URL}/assets/serenade.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 9,
        name: "Nocturne",
        image: [`${process.env.PUBLIC_URL}/assets/nocturne.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 10,
        name: "Requiem",
        image: [`${process.env.PUBLIC_URL}/assets/requiem.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 11,
        name: "Prélude",
        image: [`${process.env.PUBLIC_URL}/assets/prelude.png`],
        number: 0,
        limit: 1,
      },
      {
        id:12,
        name:"cancel",
        image:[`${process.env.PUBLIC_URL}/assets/cross.png`],
        number:0,
        limit:0,
      }
    ],
  },
  {
    dungeons: [
      {
        id: 0,
        name: "Kokiri Emerald",
        image: [`${process.env.PUBLIC_URL}/assets/emerald.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 1,
        name: "Goron Ruby",
        image: [`${process.env.PUBLIC_URL}/assets/ruby.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 2,
        name: "Zora Sapphire",
        image: [`${process.env.PUBLIC_URL}/assets/sapphire.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 3,
        name: "Forest medallion",
        image: [`${process.env.PUBLIC_URL}/assets/forest.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 4,
        name: "Fire medallion",
        image: [`${process.env.PUBLIC_URL}/assets/fire.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 5,
        name: "Water Medallion",
        image: [`${process.env.PUBLIC_URL}/assets/water.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 6,
        name: "Shadow medallion",
        image: [`${process.env.PUBLIC_URL}/assets/shadow.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 7,
        name: "Spirit medallion",
        image: [`${process.env.PUBLIC_URL}/assets/spirit.png`],
        number: 0,
        limit: 1,
      },
      {
        id: 8,
        name: "Light medallion",
        image: [`${process.env.PUBLIC_URL}/assets/light.png`],
        number: 0,
        limit: 1,
      },
    ],
  },
];
