import useLostWoodsLogic from "../logic/areas/useLostWoodsLogic";
import useSFMLogic from "../logic/areas/useSFMLogic";
import useDekuLogic from "../logic/areas/useDekuLogic";
import useForestTempleLogic from "../logic/areas/useForestTempleLogic";
import useHyruleFieldLogic from "../logic/areas/useHyruleFieldLogic";
import useLakeHyliaLogic from "../logic/areas/useLakeHyliaLogic";
import useBotwLogic from "../logic/areas/useBotwLogic";
import useDesertColossusLogic from "../logic/areas/useDesertColossusLogic";
import useShadowTempleLogic from "../logic/areas/useShadowTempleLogic";
import useRanchLogic from "../logic/areas/useRanchLogic";
import useDMCLogic from "../logic/areas/useDMCLogic";
import useDMTLogic from "../logic/areas/useDMTLogic";
import useGoronCityLogic from "../logic/areas/useGoronCityLogic";
import useKakarikoLogic from "../logic/areas/useKakarikoLogic";
import useMarketLogic from "../logic/areas/useMarketLogic";
import useGerudosFortressLogic from "../logic/areas/useGerudosFortressLogic";
import useGerudosValleyLogic from "../logic/areas/useGerudosValleyLogic";
import useGraveyardLogic from "../logic/areas/useGraveyardLogic";
import useZoraRiverLogic from "../logic/areas/useZoraRiverLogic";
import useZoraDomainLogic from "../logic/areas/useZoraDomainLogic";
import useZoraFountainLogic from "../logic/areas/useZoraFountainLogic";
import useHyruleCastleLogic from "../logic/areas/useHyruleCastleLogic";
import useIceCavernLogic from "../logic/areas/useIceCavernLogic";
import useJabuLogic from "../logic/areas/useJabuLogic";
import useWastelandLogic from "../logic/areas/useWastelandLogic";
import useOutsideGanonsCastleLogic from "../logic/areas/useOutsideGanonsCastleLogic";
import useTempleOfTimeLogic from "../logic/areas/useTempleOfTimeLogic";
import useKokiriForestLogic from "../logic/areas/useKokiriForestLogic";
import useGTGLogic from "../logic/areas/useGTGLogic";
import useWaterTempleLogic from "../logic/areas/useWaterTempleLogic";
import useFireTempleLogic from "../logic/areas/useFireTempleLogic";
import useSpiritTempleLogic from "../logic/areas/useSpiritTempleLogic";
import useGanonsCastleLogic from "../logic/areas/useGanonsCastleLogic";

function useLogic() {
  useKokiriForestLogic();
  useLostWoodsLogic();
  useSFMLogic();
  useDekuLogic();
  useForestTempleLogic();
  useHyruleFieldLogic();
  useLakeHyliaLogic();
  useRanchLogic();
  useBotwLogic();
  useDesertColossusLogic();
  useShadowTempleLogic();
  useDMCLogic();
  useDMTLogic();
  useGoronCityLogic();
  useKakarikoLogic();
  useMarketLogic();
  useGerudosFortressLogic();
  useGerudosValleyLogic();
  useGraveyardLogic();
  useZoraRiverLogic();
  useZoraDomainLogic();
  useZoraFountainLogic();
  useTempleOfTimeLogic();
  useHyruleCastleLogic();
  useHyruleFieldLogic();
  useIceCavernLogic();
  useJabuLogic();
  useWastelandLogic();
  useOutsideGanonsCastleLogic();
  useGTGLogic();
  useWaterTempleLogic();
  useSpiritTempleLogic();
  useFireTempleLogic();
  useGanonsCastleLogic();
}

export default useLogic;
